remote: true

experienceLevel:
  internship: false
  entry: false
  associate: false
  mid-senior level: true
  director: true
  executive: true

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: false
  other: false
  volunteer: false

date:
  all time: false
  month: false
  week: true
  24 hours: false

positions:
  - generative ai

locations:
  - USA
  # - Germany
  # - Canada
  # - UK

apply_once_at_company: true

distance: 100

company_blacklist:
  - wayfair
  

title_blacklist:
  - sales
  - marketing

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'
