remote: true

experienceLevel:
  internship: false
  entry: false
  associate: true
  mid-senior level: true
  director: true
  executive: true

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: false
  other: false
  volunteer: false

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  # - Chatgpt
  - Artificial Intelligence Engineer
  - generative ai  
  - Artificial Intelligence Consultant  
  - prompt engineering
  # - AI tech lead
  # - AI trainer
  - AI Project Manager
  # - Software Development Manager
  - AI consultant
  - AI Engineer
  
  

locations:
  - USA
  - Germany
  - Canada
  - UK
  # - European Economic Area
  # - Asia

apply_once_at_company: true

distance: 100

company_blacklist:
  - wayfair
  - mindrift
  

title_blacklist:
  - sales
  - marketing
  - dotnet
  - devops
  - sap
  - kotlin
  - scala
  - ruby
  - ServiceNow
  - Tableau
  - Solidity
  - IOT
  - C++
  - Java
  - .NET

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 300

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'
